logging:
    file:
        name: logs/sboard.log
    level:
        jdbc:
            connection: info
            resulsettable: info
            sqlonly: info
            sqltiming: info
        root: info
server:
    port: 8080
    servlet:
        context-path: /sboard

mybatis:
    mapper-locations: classpath:mappers/**/*.xml

spring:
    application:
        name: sboard
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: abc1234
        url: jdbc:mysql://127.0.0.1:3306/jboard
        username: dpsk3048
    devtools:
        livereload:
            enabled: true


    # 이메일 설정
    mail:
        host: smtp.gmail.com
        port: 587
        username: dpsk08270@gmail.com
        password: ltlb tzjh gdcd sdyq
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true



    jpa:
        database: mysql
        hibernate:
            # 배포할 때는 none, 개발할 때는 update
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    # 파일 업로드 설정
    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB

# 파일 경로 설정
file:
    upload:
        path: uploads/
        
        
# 서버 자동 재시작 끄기
restart:
    enabled: false