logging:
    file:
        name: log/ch09.log
    level:
        jdbc:
            connection: info
            resulsettable: info
            sqlonly: info
            sqltiming: info
        root: info
server:
    port: 8080
    servlet:
        context-path: /ch09
spring:
    application:
        name: ch09
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: abc1234
        url: jdbc:mysql://127.0.0.1:3306/studydb
        username: dpsk3048
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
